### PR TITLE
Initial implementation

### PR DESCRIPTION
**Pull request by Reithan**

### CODE REVIEW

**Comment by Reithan** [comment]
Accidentally targeted parent rather than fork due to unclear prompt on github UI

**Comment by azaghal** [comment]
Heh... No worries, although... If you have improvements for the current targeting algorithm, why not propose changes against this fork instead of spinning up another one?

I would be more than happy to accept any kind of well written improvements (although I must warn you I might end-up being a bit of a pain to work with PR reviews :) ).

**Comment by Reithan** [comment]
I'll see what I can do to make something for re-integration. I have the algorithm in a place I like now and was beginning to work on other improvements.

**Comment by azaghal** [comment]
Hey, that's fully up to you, I am one of those people that think that being able to fork a project is a big plus (as opposed to those that are insistent on anti-fragmentation) :)

Btw, if you wanted to merge changes back into this fork, I would prefer if they were smaller PRs that target specific function. Just something to consider before you make too many larger changes in case you opt to merge things back in. :)

**Comment by Reithan** [comment]
Opened a pull request with just the improved target optimization algorithm in #3

**Pull request closed without merging**
